# env settings
language: node_js
node_js: 9
# travis script adaptions
branches:
  only:
  - master
  - development
  - /^greenkeeper/.*$/

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

before_install:
    - npm install -g gulp-cli

install:
    - npm install
    - chmod 755 ./stack/scripts/ -R

script:
- npm run script gh-pages/init
- npm run lint
- npm run test
- npm run build

deploy:
  provider: script
  script: bash stack/scripts/gh-pages/deploy.sh
  on:
    branch: master
