# env settings
language: node_js
node_js: 9
# travis script adaptions
branches:
  only:
  - master
  - development
  - /^greenkeeper/.*$/

before_install:
    - npm install -g gulp-cli

install:
    - npm install
    - chmod 755 ./stack/scripts/ -R

script:
- npm run script gh-pages/init
- npm run lint
- npm run test
- npm run build
- npm run script gh-pages/deploy
