# env settings
language: node_js
node_js: 9
# travis script adaptions
branches:
  only:
  - master
  - development
  - /^greenkeeper/.*$/

before_install:
    - npm install -g gulp-cli

install: npm install

script:
- npm run lint
- npm run test
- npm run build

before_deploy:
    - 'curl -u doubleu23:62d6f361604121c33670e9987a742f1821331c51 https://api.github.com/user'

deploy:
    on:
        branch: master
    provider: pages
    local-dir: build
    skip-cleanup: true
    github-token: 62d6f361604121c33670e9987a742f1821331c51
    keep-history: true
