language: node_js
node_js:
    - 10
    - 9
    - 8

branches:
  only:
  - master
  - development
  - /^greenkeeper/.*$/

before_install:
    - npm install -g gulp-cli

install: npm install

script:
- npm run lint
- npm run test
- npm run build

# before_deploy:
#     - 'curl -u doubleu23:$GITHUB_TOKEN https://api.github.com/user'

# auth broken?
# see
# https://travis-ci.com/stackr23/react23/builds/91146957
# deploy:
#     on:
#         branch: master
#     provider: pages
#     local-dir: build
#     skip-cleanup: true
#     github-token: $GITHUB_TOKEN
#     keep-history: true

