# env settings
language: node_js
node_js: 9
# travis script adaptions
branches:
  only:
  - master
  - development
  - /^greenkeeper/.*$/

before_install:
    - npm install -g gulp-cli

install:
    - npm install

script:
# - npm run lint # add task after cleanup
- npm run test
- npm run build
