jobs:
  test_build:
    environment:
      NODE_ENV: production
      DEBUG: true
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install gulp gulp-cli --save-dev && npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - test_build
