jobs:
  test_start:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install gulp gulp-cli --save-dev && npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Start
          command: npm run start

workflows:
  version: 2
  build:
    jobs:
      - test_start
