jobs:
  build_test:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install gulp gulp-cli --save-dev && npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build_test
